import Head from 'next/head'
import HomeTab from '../components/Home/Home'


export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='theme-color' content='#58A0E2' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
       <HomeTab />
      </>
      </div>
  )
}